# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mesh_pb2 as mesh__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshNodeStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushBundle = channel.unary_unary(
                '/mesh.MeshNode/PushBundle',
                request_serializer=mesh__pb2.PushRequest.SerializeToString,
                response_deserializer=mesh__pb2.PushAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/mesh.MeshNode/Heartbeat',
                request_serializer=mesh__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mesh__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class MeshNodeServicer:
    """Missing associated documentation comment in .proto file."""

    def PushBundle(self, request, context):
        """Deliver a bundle to this node during an active contact window.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Liveness / chaos-testing check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.PushBundle,
                    request_deserializer=mesh__pb2.PushRequest.FromString,
                    response_serializer=mesh__pb2.PushAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mesh__pb2.HeartbeatRequest.FromString,
                    response_serializer=mesh__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mesh.MeshNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mesh.MeshNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshNode:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.MeshNode/PushBundle',
            mesh__pb2.PushRequest.SerializeToString,
            mesh__pb2.PushAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mesh.MeshNode/Heartbeat',
            mesh__pb2.HeartbeatRequest.SerializeToString,
            mesh__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
