# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mesh.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'mesh.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmesh.proto\x12\x04mesh\"\xaf\x01\n\x06\x42undle\x12\x11\n\tbundle_id\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65st_id\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\t\x12\x0f\n\x07size_kb\x18\x05 \x01(\x05\x12\x14\n\x0c\x63reated_at_s\x18\x06 \x01(\x01\x12\r\n\x05ttl_s\x18\x07 \x01(\x01\x12\x11\n\thop_count\x18\x08 \x01(\x05\x12\x13\n\x0bpath_so_far\x18\t \x03(\t\">\n\x0bPushRequest\x12\x1c\n\x06\x62undle\x18\x01 \x01(\x0b\x32\x0c.mesh.Bundle\x12\x11\n\tfrom_node\x18\x02 \x01(\t\"+\n\x07PushAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"7\n\x10HeartbeatRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nsim_time_s\x18\x02 \x01(\x01\"3\n\x11HeartbeatResponse\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\r\n\x05\x61live\x18\x02 \x01(\x08\x32x\n\x08MeshNode\x12.\n\nPushBundle\x12\x11.mesh.PushRequest\x1a\r.mesh.PushAck\x12<\n\tHeartbeat\x12\x16.mesh.HeartbeatRequest\x1a\x17.mesh.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mesh_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BUNDLE']._serialized_start=21
  _globals['_BUNDLE']._serialized_end=196
  _globals['_PUSHREQUEST']._serialized_start=198
  _globals['_PUSHREQUEST']._serialized_end=260
  _globals['_PUSHACK']._serialized_start=262
  _globals['_PUSHACK']._serialized_end=305
  _globals['_HEARTBEATREQUEST']._serialized_start=307
  _globals['_HEARTBEATREQUEST']._serialized_end=362
  _globals['_HEARTBEATRESPONSE']._serialized_start=364
  _globals['_HEARTBEATRESPONSE']._serialized_end=415
  _globals['_MESHNODE']._serialized_start=417
  _globals['_MESHNODE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
